export const filmCardStyle = {
  backgroundStyle: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    height: 118,
    width: "100%",
    margintop: "5%",
    borderRadius: 15,
  },
  filmTitleStyle: {
    fontSize: 16,
    color: "white",
    position: "absolute",
    fontFamily: "sans-serif-condensed",
    textAlign: "justify",
    left: 128,
    top: 8,
  },
  filmDirectorStyle: {
    fontSize: 12,
    color: "#ACACAC",
    fontFamily: "sans-serif-condensed",
    position: "absolute",
    left: 128,
    top: 32,
  },
  IMDbTextStyle: {
    position: "absolute",
    top: 74,
    left: 128,
    backgroundColor: "#FED53A",
    fontSize: 12,
    height: 20,
    width: 64,
    borderRadius: 5,
    color: "black",
    paddingLeft: 6,
    paddingTop: 1.5,
    fontWeight: "bold",
  },
  filmPosterStyle: {
    position: "absolute",
    left: 32,
    top: 5,
    width: 73,
    height: 107,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
};