export const filmCardStyle = {
  backgroundStyle: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    height: 118,
    width: "100%",
    position: "relative",
    borderRadius: 15,
  },
  filmTitleStyle: {
    fontSize: 14,
    color: "white",
    position: "absolute",
    left: 128,
    top: 8,
  },
  filmDirectorStyle: {
    fontSize: 10,
    color: "#ACACAC",
    position: "absolute",
    left: 128,
    top: 32,
  },
  IMDbTextStyle: {
    position: "absolute",
    top: 54,
    left: 128,
    backgroundColor: "#FED53A",
    fontSize: 12,
    height: 18,
    width: 64,
    borderRadius: 9,
    color: "black",
    paddingLeft: 6,
    paddingTop: 1,
  },
  filmPosterStyle: {
    position: "absolute",
    left: 32,
    top: 5,
    width: 73,
    height: 107,
    borderRadius: 5,
  },
};