export const filmCardStyle = {
  backgroundStyle: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 0.5,
    borderColor: "rgba(255, 255, 255, 0.20)",
    height: 118,
    width: "100%",
    marginTop: "1.5%",
    borderRadius: 15,
    padding: "1%",
    paddingRight: "5%",
    paddingLeft: "5%",
    flexDirection: "row",
  },
  filmTitleStyle: {
    fontSize: 16,
    marginTop: "-1%",
    color: "white",
    fontFamily: "sans-serif-condensed",
    minWidth: "90%",
    maxWidth: "92%"
  },
  filmDirectorStyle: {
    fontSize: 12,
    color: "#ACACAC",
    fontFamily: "sans-serif-condensed",
    marginTop: 2,
  },
  IMDbTextStyle: {
    backgroundColor: "#FED53A",
    fontSize: 12,
    height: 20,
    width: 64,
    borderRadius: 5,
    color: "black",
    paddingLeft: 6,
    paddingTop: 1.5,
    fontWeight: "bold",
  },
  filmPosterStyle: {
    width: 73,
    height: "100%",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
};